- name: conditions
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: please enter number
    private: no
  tasks:
  - name: number is less than 15
    ansible.builtin.debug:
      msg: "Given number {{number}} is less than 15"
    when: number | int < 15

  - name: number is greater than or equal to 15
    ansible.builtin.debug:
      msg: "Given number {{number}} is greater than or equal to 15"
    when: number | int >= 15