- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"

- name: uppercase
  hosts: localhost
  vars:
    greeting: "Hi, Good Afternoon"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}" 

- name: lowercase
  hosts: localhost
  vars:
    greeting: "Hi, Good Afternoon"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1, 3, 3, 4, 4, 5, 6, 7, 9]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

- name: print min age and max age
  hosts: localhost
  vars:
    ages: [16, 25, 34, 65, 79, 90]
  tasks: 
  - name: print min age and max age
    ansible.builtin.debug:
      msg: "min age: {{ages | min}}, max age: {{ages | max}}"                       